repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
    -   id: ruff
        args: [--fix]
        files: ^hayhooks/  # Target only files in the hayhooks directory
    -   id: ruff-format
        files: ^hayhooks/  # Target only files in the hayhooks directory