[project]
name = "groundedllm-hayhooks"
version = "0.1.0"
description = "Hayhooks"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "gdown>=5.2.0",
    "hayhooks[mcp]>=0.6.0",
    "haystack-ai>=2.12.0",
    "letta-client>=0.1.91",
    "markdown-it-py>=3.0.0",
    "mdit-plain>=1.0.1",
    "openapi-llm>=0.4.2",
    "openapi3>=1.8.2",
    "pydantic-settings>=2.8.1",
    "pypdf>=5.4.0",
    "python-docx>=1.1.2",
    "rich>=13.7.1",
    "tavily-python>=0.5.3",
    "trafilatura>=2.0.0",
]

[project.optional-dependencies]
test = [
    "pytest>=8.0",
    "pytest-mock>=3.12",
]

[tool.setuptools]
packages = ["components", "pipelines", "resources"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
