[project]
name = "groundedllm-hayhooks"
version = "0.1.0"
description = "Hayhooks"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "hayhooks[mcp]>=0.6.0",
    "haystack-ai>=2.12.0",
    "letta-client>=0.1.91",
    "openapi-llm>=0.4.2",
    "openapi3>=1.8.2",
    "pydantic-settings>=2.8.1",
    "rich>=13.7.1",
    "tavily-python>=0.5.3",
    "trafilatura>=2.0.0",
]

[project.optional-dependencies]
test = [
    "pytest>=8.0",
    "pytest-mock>=3.12",
]
