services:

  # This is too noisy to be worth it
  # aws-documentation-mcp-server:
  #   build: aws-documentation-mcp-server/
  #   container_name: aws-documentation-mcp-server
  #   ports:
  #     - 9712:9712
  #   environment:
  #     - LOG_LEVEL=ERROR
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://127.0.0.1:9712/sse"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 18
  #     start_period: 5s

  wikipedia-mcp-server:
    build: wikipedia-mcp-server/
    container_name: wikipedia-mcp-server
    ports:
      - 9713:9713
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9713/sse"]
      interval: 10s
      timeout: 5s
      retries: 18
      start_period: 5s

  letta-mcp-server:
    build: letta-mcp-server/
    container_name: letta-mcp-server
    ports:
      - 9714:9714
    environment:
      - LETTA_BASE_URL=http://letta:8283
      - PORT=9714
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9714/sse"]
      interval: 10s
      timeout: 5s
      retries: 18
      start_period: 5s

  github-mcp-server:
    build: github-mcp-server/
    container_name: github-mcp-server
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=$GITHUB_PERSONAL_ACCESS_TOKEN
      - GITHUB_TOOLSETS=all
    ports:
      - 9720:9720
    