use_default_settings: true

general:
  instance_name: 'searxng'

search:
  autocomplete: 'google'
  formats:
    - html
    - json

server:
  secret_key: 'a2fb23f1b02e6ee83875b09826990de0f6bd908b6638e8c10277d415f6ab852b' # Is overwritten by ${SEARXNG_SECRET}

engines:
  - name: wolframalpha
    disabled: false

  # - name: brave
  #   engine: brave
  #   shortcut: br
  #   time_range_support: true
  #   paging: true
  #   categories: [general, web]
  #   brave_category: search
  #   # brave_spellcheck: true
  #   disabled: true
